# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('historia', models.TextField()),
                ('poder', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='images')),
            ],
        ),
    ]
